/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ece454750s15a1;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ServerData implements org.apache.thrift.TBase<ServerData, ServerData._Fields>, java.io.Serializable, Cloneable, Comparable<ServerData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServerData");

  private static final org.apache.thrift.protocol.TField KNOWN_SERVERS_FIELD_DESC = new org.apache.thrift.protocol.TField("knownServers", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ServerDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ServerDataTupleSchemeFactory());
  }

  public List<ServerDescription> knownServers; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KNOWN_SERVERS((short)1, "knownServers");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KNOWN_SERVERS
          return KNOWN_SERVERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KNOWN_SERVERS, new org.apache.thrift.meta_data.FieldMetaData("knownServers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ServerDescription.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServerData.class, metaDataMap);
  }

  public ServerData() {
  }

  public ServerData(
    List<ServerDescription> knownServers)
  {
    this();
    this.knownServers = knownServers;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServerData(ServerData other) {
    if (other.isSetKnownServers()) {
      List<ServerDescription> __this__knownServers = new ArrayList<ServerDescription>(other.knownServers.size());
      for (ServerDescription other_element : other.knownServers) {
        __this__knownServers.add(new ServerDescription(other_element));
      }
      this.knownServers = __this__knownServers;
    }
  }

  public ServerData deepCopy() {
    return new ServerData(this);
  }

  @Override
  public void clear() {
    this.knownServers = null;
  }

  public int getKnownServersSize() {
    return (this.knownServers == null) ? 0 : this.knownServers.size();
  }

  public java.util.Iterator<ServerDescription> getKnownServersIterator() {
    return (this.knownServers == null) ? null : this.knownServers.iterator();
  }

  public void addToKnownServers(ServerDescription elem) {
    if (this.knownServers == null) {
      this.knownServers = new ArrayList<ServerDescription>();
    }
    this.knownServers.add(elem);
  }

  public List<ServerDescription> getKnownServers() {
    return this.knownServers;
  }

  public ServerData setKnownServers(List<ServerDescription> knownServers) {
    this.knownServers = knownServers;
    return this;
  }

  public void unsetKnownServers() {
    this.knownServers = null;
  }

  /** Returns true if field knownServers is set (has been assigned a value) and false otherwise */
  public boolean isSetKnownServers() {
    return this.knownServers != null;
  }

  public void setKnownServersIsSet(boolean value) {
    if (!value) {
      this.knownServers = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case KNOWN_SERVERS:
      if (value == null) {
        unsetKnownServers();
      } else {
        setKnownServers((List<ServerDescription>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case KNOWN_SERVERS:
      return getKnownServers();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case KNOWN_SERVERS:
      return isSetKnownServers();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ServerData)
      return this.equals((ServerData)that);
    return false;
  }

  public boolean equals(ServerData that) {
    if (that == null)
      return false;

    boolean this_present_knownServers = true && this.isSetKnownServers();
    boolean that_present_knownServers = true && that.isSetKnownServers();
    if (this_present_knownServers || that_present_knownServers) {
      if (!(this_present_knownServers && that_present_knownServers))
        return false;
      if (!this.knownServers.equals(that.knownServers))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ServerData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetKnownServers()).compareTo(other.isSetKnownServers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKnownServers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.knownServers, other.knownServers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ServerData(");
    boolean first = true;

    sb.append("knownServers:");
    if (this.knownServers == null) {
      sb.append("null");
    } else {
      sb.append(this.knownServers);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServerDataStandardSchemeFactory implements SchemeFactory {
    public ServerDataStandardScheme getScheme() {
      return new ServerDataStandardScheme();
    }
  }

  private static class ServerDataStandardScheme extends StandardScheme<ServerData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ServerData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KNOWN_SERVERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.knownServers = new ArrayList<ServerDescription>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  ServerDescription _elem2;
                  _elem2 = new ServerDescription();
                  _elem2.read(iprot);
                  struct.knownServers.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setKnownServersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ServerData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.knownServers != null) {
        oprot.writeFieldBegin(KNOWN_SERVERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.knownServers.size()));
          for (ServerDescription _iter3 : struct.knownServers)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServerDataTupleSchemeFactory implements SchemeFactory {
    public ServerDataTupleScheme getScheme() {
      return new ServerDataTupleScheme();
    }
  }

  private static class ServerDataTupleScheme extends TupleScheme<ServerData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServerData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetKnownServers()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetKnownServers()) {
        {
          oprot.writeI32(struct.knownServers.size());
          for (ServerDescription _iter4 : struct.knownServers)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServerData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.knownServers = new ArrayList<ServerDescription>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            ServerDescription _elem7;
            _elem7 = new ServerDescription();
            _elem7.read(iprot);
            struct.knownServers.add(_elem7);
          }
        }
        struct.setKnownServersIsSet(true);
      }
    }
  }

}

